### ISSUE TITLE
Is this a good idea?

### ISSUE THREAD

**Issue by potch** [mozilla/boards#1]
I'm not really sure yet- I was inspired by [this Bocoup blog post](http://bocoup.com/weblog/bocoups-most-important-empty-repo/), and really like how lightweight the idea is. Plus, who doesn't need another wiki?

**Comment by sole** [comment]
What is the discussion about? or can I start yakshaving without context? :palm_tree:

**Comment by potch** [comment]
> can I start yakshaving without context? :palm_tree:

Definitely.

**Comment by sole** [comment]
Tabs!

**Comment by potch** [comment]
> Tabs!

📁📂
